### ISSUE TITLE
Blockparser gets irritated by Combination of / and --

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tSQLScriptParser#1]
When using the Blockparsermode the following Script results in wrong parsing:

BEGIN
  NULL;
  NULL;
END;
/
-- my comment
BEGIN
  NULL;
END;

The first block is recognized sucessfully, The second block is split at all semicolons instead of beeing kept together until the END; instruction.
Removing the comment or the slash is a workaround.

**Comment by jlolling** [comment]
OK, I got it. I will update the component.

**Comment by jlolling** [comment]
This issue is now solved in version 1.6.
Please take care, this new release depends on Java 8.
