### ISSUE TITLE
Error with ":" in the SQL script

### ISSUE THREAD

**Issue by rgurskis** [jlolling/talendcomp_tSQLScriptParser#3]
Component is not handling SQL script with colons (":")  properly. 
These can be used when parsing JSON data in Snowflake SQL dialect
https://docs.snowflake.net/manuals/user-guide/querying-semistructured.html#traversing-semi-structured-data

Error produced by tJDBCRow component: 
`net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
syntax error line X at position X unexpected '?'.`

Sample SQL script:
`SELECT log:host::string FROM log_table;`

**Comment by jlolling** [comment]
The problem is, the parser recognise :host as bind variable. In your use case this is not a bind variable, instead it is a syntax to navigate through structured data.
I have to add an option to switch off the detection of bind variables.
I will do that asap.

**Comment by jlolling** [comment]
Please try the release 1.5 which has an option to prevent detecting bin variables. I have published it as release here in Github.

**Comment by rgurskis** [comment]
Yes, it is working now. Thank you :)
